export const allArticles = [
    {
        id: 1,
        owner: 1,
        title: "Fetch, a place for females and non-binary people to talk all things tech",
        pub_date: "2022-05-20T15:18:23.382748Z",
	    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non quam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Magna ac placerat vestibulum lectus.",
	    image:"https://unsplash.com/photos/SYTO3xs06fU",
	    category:"Misc"
    },
    {
        id: 2,
        owner: 1,
        title: "How to approach Django documentation",
        pub_date: "2022-05-21T09:27:23.382748Z",
	    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non quam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Magna ac placerat vestibulum lectus.",
	    image:"https://unsplash.com/photos/g0RtZc1IBtU",
	    category:"Django"
    },
    {
        id: 3,
        owner: 4,
        title: "Skinny jeans and building React routes",
        pub_date: "2022-05-17T16:54:21.382748Z",
	    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non quam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Magna ac placerat vestibulum lectus.",
	    image:"https://unsplash.com/photos/0dLJWa40dqM",
	    category:"React"
    },
    {
        id: 4,
        owner: 2,
        title: "Machine learning with Python",
        pub_date: "2022-05-09T09:41:43.382748Z",
	    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non quam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Magna ac placerat vestibulum lectus.",
	    image:"https://unsplash.com/photos/w7ZyuGYNpRQ",
	    category:"Python"
    }, 
];

export const allProfiles = [
    {
        id: 1,
        username: "Julie Hotdogs",
        password: "pbkdf2_sha256$320000$ip489WwPHMXpsOPVRbgqYL$gXeVtLmNfhgx3BuzNxPAYZvHc4URuaRAFngET0jhbbY=",
        is_mentor: true,
        is_student: false,
        profile_photo: "https://cdn5.vectorstock.com/i/1000x1000/73/04/female-avatar-profile-icon-round-woman-face-vector-18307304.jpg",
        banner_photo: "https://media.istockphoto.com/photos/abstract-big-data-representation-in-red-color-with-binary-numbers-and-picture-id1317246838?b=1&k=20&m=1317246838&s=170667a&w=0&h=u8Dv1VhH2_RXdVxJG-yya0kCqLxDqmU9o5cJ_S40YDE=",
        location: "Perth",
        social_link: "www.facebook.com",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices gravida dictum fusce ut placerat orci nulla. Integer feugiat scelerisque varius morbi enim nunc. At volutpat diam ut venenatis tellus in metus vulputate eu. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nulla pellentesque dignissim enim sit amet. Eget velit aliquet sagittis id consectetur purus ut faucibus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Amet venenatis urna cursus eget nunc. Viverra vitae congue eu consequat. Non consectetur a erat nam at lectus urna. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Nisi porta lorem mollis aliquam. Eget lorem dolor sed viverra ipsum nunc aliquet.",
        coffee: false,
        mentoring: true,
        tutoring: false,
        public_speaking: false
    },
    {
        id: 2,
        username: "Meng Zu",
        password: "pbkdf2_sha256$320000$ip489WwPHMXpsOPVRbgqYL$gXeVtLmNfhgx3BuzNxPAYZvHc4URuaRAFngET0jhbbY=",
        is_mentor: true,
        is_student: false,
        profile_photo: "https://www.pngitem.com/pimgs/m/0-6243_user-profile-avatar-scalable-vector-graphics-icon-woman.png",
        banner_photo: "https://image.shutterstock.com/image-vector/vector-banner-design-circuit-board-260nw-1233925105.jpg",
        location: "Mount Lawley",
        social_link: "www.facebook.com",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices gravida dictum fusce ut placerat orci nulla. Integer feugiat scelerisque varius morbi enim nunc. At volutpat diam ut venenatis tellus in metus vulputate eu. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nulla pellentesque dignissim enim sit amet. Eget velit aliquet sagittis id consectetur purus ut faucibus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Amet venenatis urna cursus eget nunc. Viverra vitae congue eu consequat. Non consectetur a erat nam at lectus urna. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Nisi porta lorem mollis aliquam. Eget lorem dolor sed viverra ipsum nunc aliquet.",
        coffee: true,
        mentoring: true,
        tutoring: false,
        public_speaking: true
    },
    {
        id: 3,
        username: "Bernie Marit",
        password: "pbkdf2_sha256$320000$ip489WwPHMXpsOPVRbgqYL$gXeVtLmNfhgx3BuzNxPAYZvHc4URuaRAFngET0jhbbY=",
        is_mentor: false,
        is_student: true,
        profile_photo: "https://cdn5.vectorstock.com/i/1000x1000/72/59/female-avatar-profile-icon-round-african-american-vector-18307259.jpg",
        banner_photo: "https://medvectortrials.com/wp-content/uploads/2018/04/Home-Four-Banner-Background-Image.png",
        location: "Fremantle",
        social_link: "www.facebook.com",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices gravida dictum fusce ut placerat orci nulla. Integer feugiat scelerisque varius morbi enim nunc. At volutpat diam ut venenatis tellus in metus vulputate eu. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nulla pellentesque dignissim enim sit amet. Eget velit aliquet sagittis id consectetur purus ut faucibus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Amet venenatis urna cursus eget nunc. Viverra vitae congue eu consequat. Non consectetur a erat nam at lectus urna. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Nisi porta lorem mollis aliquam. Eget lorem dolor sed viverra ipsum nunc aliquet.",
        coffee: false,
        mentoring: false,
        tutoring: false,
        public_speaking: false
    },
    {
        id: 4,
        username: "Hilde Rebecca",
        password: "pbkdf2_sha256$320000$ip489WwPHMXpsOPVRbgqYL$gXeVtLmNfhgx3BuzNxPAYZvHc4URuaRAFngET0jhbbY=",
        is_mentor: true,
        is_student: false,
        profile_photo: "https://i.pinimg.com/originals/a6/58/32/a65832155622ac173337874f02b218fb.png",
        banner_photo: "https://www.publicdomainpictures.net/pictures/150000/nahled/banner-header-tapete-1450520058Odj.jpg",
        location: "Fremantle",
        social_link: "www.facebook.com",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices gravida dictum fusce ut placerat orci nulla. Integer feugiat scelerisque varius morbi enim nunc. At volutpat diam ut venenatis tellus in metus vulputate eu. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nulla pellentesque dignissim enim sit amet. Eget velit aliquet sagittis id consectetur purus ut faucibus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Amet venenatis urna cursus eget nunc. Viverra vitae congue eu consequat. Non consectetur a erat nam at lectus urna. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Nisi porta lorem mollis aliquam. Eget lorem dolor sed viverra ipsum nunc aliquet.",
        coffee: true,
        mentoring: true,
        tutoring: true,
        public_speaking: false
    },
    {
        id: 5,
        username: "Teresa Wulfric",
        password: "pbkdf2_sha256$320000$ip489WwPHMXpsOPVRbgqYL$gXeVtLmNfhgx3BuzNxPAYZvHc4URuaRAFngET0jhbbY=",
        is_mentor: false,
        is_student: true,
        profile_photo: "https://thumbs.dreamstime.com/b/female-avatar-profile-picture-vector-female-avatar-profile-picture-vector-102690279.jpg",
        banner_photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1fToGiSxLC8Bgf49_VdFFEREbsS7sG99Ndg&usqp=CAU",
        location: "Mandurah",
        social_link: "www.facebook.com",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices gravida dictum fusce ut placerat orci nulla. Integer feugiat scelerisque varius morbi enim nunc. At volutpat diam ut venenatis tellus in metus vulputate eu. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nulla pellentesque dignissim enim sit amet. Eget velit aliquet sagittis id consectetur purus ut faucibus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Amet venenatis urna cursus eget nunc. Viverra vitae congue eu consequat. Non consectetur a erat nam at lectus urna. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Nisi porta lorem mollis aliquam. Eget lorem dolor sed viverra ipsum nunc aliquet.",
        coffee: false,
        mentoring: false,
        tutoring: false,
        public_speaking: false
    },
];
